const express = require("express");
const auth = require("../../middleware/auth");
const validate = require("../../middleware/validation");
const { requireBusinessMembership } = require("../../middleware/authorization");
const { requirePermission, requireManagementRole } = require("../../middleware/permission");
const c = require("./automation.controller");
const v = require("./automation.validator");
const router = express.Router();
router.use(auth);
router.get("/business/:businessId/meta", v.metadataValidator, validate, requireBusinessMembership, requirePermission("automations.view"), c.getAutomationMetadata);
router.post("/business/:businessId", v.createAutomationValidator, validate, requireBusinessMembership, requirePermission("automations.create"), c.createAutomation);
router.get("/business/:businessId", v.listAutomationValidator, validate, requireBusinessMembership, requirePermission("automations.view"), c.getAutomations);
router.get("/business/:businessId/:automationId", v.automationIdValidator, validate, requireBusinessMembership, requirePermission("automations.view"), c.getAutomationById);
router.patch("/business/:businessId/:automationId", v.updateAutomationValidator, validate, requireBusinessMembership, requirePermission("automations.update"), c.updateAutomation);
router.patch("/business/:businessId/:automationId/status", v.statusValidator, validate, requireBusinessMembership, requirePermission("automations.update"), c.updateAutomationStatus);
router.post("/business/:businessId/:automationId/clone", v.cloneValidator, validate, requireBusinessMembership, requirePermission("automations.create"), c.cloneAutomation);
router.post("/business/:businessId/:automationId/execute", v.executeValidator, validate, requireBusinessMembership, requirePermission("automations.execute"), c.executeAutomation);
router.get("/business/:businessId/:automationId/executions", v.executionListValidator, validate, requireBusinessMembership, requirePermission("automations.view"), c.getExecutions);
router.get("/business/:businessId/executions/:executionId", v.executionIdValidator, validate, requireBusinessMembership, requirePermission("automations.view"), c.getExecutionById);
router.delete("/business/:businessId/:automationId", v.automationIdValidator, validate, requireBusinessMembership, requireManagementRole, requirePermission("automations.delete"), c.deleteAutomation);
module.exports = router;
